"""
INSTRUCTION HEADER

What this file does (plain English):
- Defines HEADERS: a dict mapping every run_config.xlsx sheet name to its
  ordered list of column names.
- This is the single source of truth for the workbook schema. Every tool that
  reads or writes the Excel workbook uses HEADERS to know which columns exist
  and in what order.
- When a new column is added to the workbook (via a migrate_*.py script or
  manually), the matching list here must be updated to keep the schema in sync.
- Used by: excel_io.py (reading), export_snapshot.py (schema embedding),
  load_snapshot.py (validation), and all tools/admin/*.py scripts.

Where it runs: Imported only. Never run directly as a script.
"""

HEADERS = {
    "RUNBOOK": [
        "StepNo",
        "Task",
        "CommandOrAction",
        "Notes",
    ],
    "PATHS": [
        "Profile",
        "IsActive",
        "CODE_ROOT",
        "DATA_ROOT",
        "DUCKDB_FILE",
        "RAW_DIR",
        "CANONICAL_DIR",
        "FEATURE_CACHE_DIR",
        "RUNS_DIR",
        "LOG_DIR",
        "EXPORT_CONFIG_DIR",
        "Notes",
    ],
    "DATASETS": [
        "dataset_id",
        "dataset_type",
        "source_type",
        "source_path_or_id",
        "update_mode",
        "date_col",
        "timestamp_tz",
        "bar_frequency",
        "known_time_rule",
        "default_availability_lag_days",
        "canonical_table_name",
        "canonical_partition_keys",
        "threshold_method",
        "threshold_min_size",
        "threshold_pct",
        "threshold_z",
        "threshold_window_days",
        "notes",
    ],
    "INSTRUMENTS": [
        "instrument_id",
        "instrument_name",
        "instrument_type",
        "prices_dataset_id",
        "open_col",
        "high_col",
        "low_col",
        "close_col",
        "volume_col",
        "units",
        "return_model",
        "tick_size",
        "multiplier",
        "currency",
        "calendar",
        "default_execution_time",
        "default_execution_price_model",
        "footprint_dataset_id",
        "footprint_proxy_dataset_id",
        "cvd_dataset_id",
        "cvd_proxy_dataset_id",
        "metric_source_mode",
        "big_trades_dataset_id",
        "big_trades_proxy_dataset_id",
        "big_trades_source_mode",
        "notes",
    ],
    "FEATURE_LIBRARY": [
        "feature_id",
        "feature_name",
        "dataset_id",
        "instrument_scope",
        "input_col",
        "transform",
        "params_json",
        "lag_days",
        "availability_lag_days",
        "missing_policy",
        "winsorize",
        "normalize",
        "tags",
        "enabled",
        "notes",
    ],
    "ENGINEERED_FEATURES": [
        "eng_feature_id",
        "eng_feature_name",
        "input_feature_ids",
        "combine_transform",
        "params_json",
        "lag_days",
        "availability_lag_days",
        "missing_policy",
        "tags",
        "enabled",
        "notes",
    ],
    "FEATURE_SETS": [
        "feature_set_id",
        "description",
        "include_tags",
        "exclude_tags",
        "include_feature_ids",
        "exclude_feature_ids",
        "max_features",
        "enabled",
        "notes",
    ],
    "SIGNAL_TEMPLATES": [
        "template_id",
        "template_name",
        "allowed_feature_inputs",
        "supports_long_short",
        "supports_flat",
        "description",
        "default_params_json",
        "enabled",
        "notes",
    ],
    "STRATEGIES": [
        "strategy_id",
        "strategy_name",
        "instrument_id",
        "feature_set_id",
        "signal_template_id",
        "primary_feature_id",
        "secondary_feature_id",
        "feature_combo_rule",
        "combo_weights_json",
        "position_mode",
        "position_values",
        "enabled",
        "notes",
    ],
    "BACKTESTS": [
        "backtest_id",
        "strategy_id",
        "start_date",
        "end_date",
        "oos_last_x_months",
        "rebalance_rule",
        "execution_time",
        "execution_price_model",
        "spread_model_type",
        "spread_value",
        "slippage_model_type",
        "slippage_value",
        "allow_flip_same_day",
        "min_hold_days",
        "cooldown_days",
        "as_of_date",
        "enabled",
        "notes",
    ],
    "OPTIMIZATION_STUDIES": [
        "study_id",
        "backtest_id",
        "method",
        "objective_primary_metric",
        "objective_secondary_metric",
        "objective_direction",
        "optimize_on",
        "n_trials",
        "seed",
        "save_top_n_artifacts",
        "constraint_set_id",
        "robustness_profile_id",
        "enabled",
        "notes",
    ],
    "OPTIMIZATION_PARAMS": [
        "study_id",
        "param_scope",
        "target_id",
        "param_name",
        "optimize_flag",
        "param_type",
        "low",
        "high",
        "step",
        "choices",
        "constraint_group",
        "constraint_rule",
        "default_value_if_not_optimized",
        "notes",
    ],
    "CONSTRAINT_SETS": [
        "constraint_set_id",
        "description",
        "enabled",
        "notes",
    ],
    "CONSTRAINTS": [
        "constraint_set_id",
        "metric_id",
        "scope",
        "operator",
        "threshold",
        "enabled",
        "severity",
        "notes",
    ],
    "METRICS": [
        "metric_id",
        "description",
        "enabled",
        "annualization_factor",
        "risk_free_rate",
        "notes",
    ],
    "ROBUSTNESS_PROFILES": [
        "robustness_profile_id",
        "description",
        "enabled",
        "notes",
    ],
    "ROBUSTNESS": [
        "robustness_profile_id",
        "test_id",
        "enabled",
        "param_json",
        "notes",
    ],
    "REPORTING": [
        "report_id",
        "target_type",
        "target_id",
        "generate_tearsheet",
        "save_equity_curve",
        "save_positions",
        "save_signals",
        "save_feature_debug",
        "leaderboard_top_n",
        "pareto_plot",
        "output_formats",
        "enabled",
        "notes",
    ],
}
